### ISSUE TITLE
ModuleNotFoundError: No module named 'frida_android_helper.crypto'

### ISSUE THREAD

**Issue by viktory36** [Hamz-a/frida-android-helper#3]
I have fixed this by swapping out to `from crpytography import *`, in `fah.py` but do clarify if there is a purpose for it being the current code.

**Comment by Hamz-a** [comment]
Hey @viktory36 !

So I was working on this new submodule "crypto" to hook known crypto functions but didn't finish it. I guess I pushed that line a bit too early... It should be safe to remove that line altogether!

**Comment by viktory36** [comment]
all good. have a great day!
